name: docker_build_push_image

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME: 
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_REPO:
        required: true
    inputs:
      DOCKER_TARGET_PLATFORM:
        type: string
        required: true
      runs-on:
        type: string
        required: false
        default: ubuntu-latest

jobs:
  docker_build_push_image:
    runs-on: ${{ inputs.runs-on }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{  secrets.DOCKERHUB_REPO }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
            type=raw,value={{branch}}-latest
            type=raw,value={{sha}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ inputs.DOCKER_TARGET_PLATFORM }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ inputs.DOCKER_TARGET_PLATFORM }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build_without_npm_token
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ inputs.DOCKER_TARGET_PLATFORM }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}