name: docker_build_push_nodeservice

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME: 
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_REPO:
        required: true
      NPM_TOKEN:
        required: true
    inputs:
      DOCKER_FILE_PATH:
        type: string
        required: false
        default: "Dockerfile"
      DOCKER_CONTEXT_PATH:
        type: string
        required: false
        default: "."
      runs-on:
        type: string
        required: false
        default: ubuntu-latest

jobs:
  docker_build_push_nodeservice:
    runs-on: ${{ inputs.runs-on }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract branch short sha
        id: git_extract_branch_sha
        shell: bash
        run: |
          echo "REPO_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "Output for sha_short is: ${{ steps.git_extract_branch_sha.outputs.REPO_SHA_SHORT }}"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image with NPM token
        run: |
          docker build --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }}  --tag ${{  secrets.DOCKERHUB_USERNAME }}/${{  secrets.DOCKERHUB_REPO }}:${{ steps.git_extract_branch_sha.outputs.REPO_SHA_SHORT }} -f ${{  inputs.DOCKER_FILE_PATH }}  ${{  inputs.DOCKER_CONTEXT_PATH }}
         
      - name: Push docker image
        run: |
          docker image push ${{  secrets.DOCKERHUB_USERNAME }}/${{  secrets.DOCKERHUB_REPO }} --all-tags